our_app/our_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include("polls.urls")),
]

our_app/polls/urls.py
from django.urls import path
from polls import views, views_gen


app_name = "polls"
# urlpatterns = [
#     path('', views.index, name="index"),
#     path('<int:question_id>/', views.detail, name='detail'),
#     path('<int:question_id>/results/', views.results, name='results'),
#     path('<int:question_id>/vote/', views.vote, name='vote'),
# ]

urlpatterns = [
    path('', views_gen.IndexView.as_view(), name="index"),
    path('<int:pk>/', views_gen.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views_gen.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('api/v1/questions/', views.question_collections),
    path('api/v1/questions/<int:id>', views.question)
]

our_app/polls/models.py
import datetime

from django.db import models
from django.utils import timezone


# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")

    def __str__(self):
        return f"{self.question_text}, id={self.id}, pub_date={self.pub_date}"
    
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

our_app/polls/views.py
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from rest_framework.decorators import api_view
from rest_framework.response import Response

from .models import Question, Choice
from .serializers import QuestionSerializer


def index(request: HttpRequest) -> HttpResponse:
    latest_question_list = Question.objects.order_by("-pub_date")[:5]
    context = {
        "latest_question_list": latest_question_list
    }
    return render(request, "polls/index.html", context)


def results(request: HttpRequest, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, "polls/results.html", {"question": question})


def detail(request: HttpRequest, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, "polls/detail.html", {"question": question})


def vote(request: HttpRequest, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        return render(request, "polls/detail.html", {
            "question": question,
            "error_message": "Ви не обрали варіант відповіді."
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
    return HttpResponseRedirect(reverse("polls:results", args=(question_id,)))


@api_view(["GET"])
def question_collections(request):
    if request.method == "GET":
        questions = Question.objects.all()
        serializer = QuestionSerializer(questions, many=True)
        return Response(serializer.data)


@api_view(["GET"])
def question(request, id):
    if request.method == "GET":
        selected_choice = question.choice_set.get(pk=id)
        serializer = QuestionSerializer(selected_choice)
        return Response(serializer.data)

our_app/polls/templates/polls/about.html
<hr>
<h6>it is my homework</h6>
<hr>

our_app/polls/templates/polls/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Polls</title>
</head>
<body>
    {% block heading %}
        <h2>my POLLS!</h2>
        <hr>
    {% endblock heading %}

    {% block content %}
    {% endblock content %}
    
</body>
</html>

our_app/polls/templates/polls/detail.html
{% extends "polls/base.html" %}

{% block heading %}
{{ block.super }}
<h4>our question:</h4>
{% endblock heading %}

{% block content %}
<form action="{% url  'polls:vote' question.id %}" method="post">
{% csrf_token %}
<fieldset>
    <legend><h3>{{question.question_text}}</h3></legend>
    {% if error_message %}<p><strong>{{error_message}}</strong></p>{% endif %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}"
        <label for="choice{{ forloop.counter }}">{{choice.choice_text}}</label><br>
    {% endfor %}
</fieldset>
<input type="submit" value="Vote">
</form>


<p>
    {% include "polls/about.html" %}
</p>
{% endblock content %}

our_app/polls/templates/polls/index.html
{% extends "polls/base.html" %}

{% block heading %}
    {{ block.super }}
    <h4>actual polls:</h4>
{% endblock heading %}

{% block content %}
{% if latest_question_list %}
<ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text|linebreaks }}</a></li>
    {% endfor %}
</ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

<p>
    {% include "polls/about.html" %}
</p>
{% endblock content %}

our_app/polls/templates/polls/results.html
{% extends "polls/base.html" %}

{% block heading %}
{{ block.super }}
<h4>result for question:</h4>
{% endblock heading %}

{% block content %}
<h3>{{ question.question_text }}</h3>
<br>

<ul>
    {% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
    {% endfor %}
</ul>

<a href="{% url 'polls:index' %}">Vote again?</a>


<p>
    {% include "polls/about.html" %}
</p>
{% endblock content %}